FROM mysql:5.7
MAINTAINER "Edson Yamada" <enyamada@gmail.com>

# /docker-entrypoint-initdb.d/ will have all the .sql files that create the necessary db, tables etc
ADD  docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/



